updated Dockerfile

diff --git a/r-shiny/Dockerfile b/r-shiny/Dockerfile
--- a/r-shiny/Dockerfile
+++ b/r-shiny/Dockerfile
@@ -1,46 +1,64 @@
-FROM afcai2c/r-base:latest
+FROM afcai2c/python-r-ai:latest
 
 USER root
 
-RUN yum update -y && \ 
-    yum upgrade -y && \
-    yum clean all -y
+RUN yum update -y         && \ 
+    yum clean all -y      && \
+    yum install -y           \
+        binutils             \
+        glibc-devel          \
+        glibc-headers        \
+        kernel-headers
 
-# These pacakges were removed from the-r-project to mitigate vulnerabilities, but are required for shiny and rmarkdown
-RUN yum install -y \
-    binutils       \
-    glibc-devel    \
-    glibc-headers  \
-    libX11         \
-    kernel-headers
+RUN mkdir -p /tmp/repo/
+COPY *.tar.gz /tmp/repo/
 
 # Creates local R repository from the /tmp/repo directory
 RUN R -e "tools::write_PACKAGES('/tmp/repo/')"
 
+USER 1001
+
+# R Script to install pacakges and provides a stop error if in installation fails
+COPY ./scripts/web_install.R .
+
 # Requested packages
-RUN R -e "install.packages(c('tidyverse', 'shiny', 'plotly', 'shinydashboard', 'DT', 'rmarkdown', 'flexdashboard'), repos='http://cran.r-project.org', INSTALL_opts='--no-html')"
+#RUN R -e "install.packages(c('tidyverse', 'shiny', 'plotly', 'shinydashboard', 'DT', 'rmarkdown', 'flexdashboard'), dependencies=TRUE, repos='https://packagemanager.rstudio.com/all/latest')"
+#RUN R -e "install.packages(c('tidyverse', 'shiny', 'plotly', 'shinydashboard', 'DT', 'rmarkdown', 'flexdashboard'), dependencies=TRUE, repos=NULL, recursive=TRUE, contriburl='file://tmp/repo/')"
+RUN Rscript --no-save web_install.R   \
+    tidyverse        \
+    shiny            \
+    plotly           \
+    shinydashboard   \
+    DT               \
+    rmarkdown        \
+    flexdashboard
 
-RUN yum -y install curl
 
-WORKDIR /repo
+RUN curl -O https://download3.rstudio.org/centos7/x86_64/shiny-server-1.5.16.958-x86_64.rpm
 
-RUN curl -LO https://download3.rstudio.org/centos7/x86_64/shiny-server-1.5.16.958-x86_64.rpm
+USER root
 
-RUN yum -y install --nogpgcheck shiny-server-1.5.16.958-x86_64.rpm && \
-	rm -rf shiny-server-1.5.16.958-x86_64.rpm
+RUN yum install -y --nogpgcheck shiny-server-1.5.16.958-x86_64.rpm   && \
+	rm -f shiny-server-1.5.16.958-x86_64.rpm
 
-RUN usermod shiny -g 0
+RUN mkdir -p /var/log/shiny-server /var/lib/shiny-server/bookmarks                        && \
+	chown 1001 /var/log/shiny-server /var/lib/shiny-server/bookmarks                      && \
+	chown 1001 -R /srv/shiny-server                                                       && \
+	chmod 755 -R /srv/shiny-server                                                        && \
+	chown 1001 -R /opt/shiny-server/samples/sample-apps /var/lib/shiny-server/bookmarks   && \
+	chmod 755 -R /opt/shiny-server/samples/sample-apps
 
-RUN mkdir -p /var/log/shiny-server /var/lib/shiny-server/bookmarks \
-	&& chown shiny:shiny /var/log/shiny-server /var/lib/shiny-server/bookmarks \
-	&& chown shiny:shiny -R /srv/shiny-server \
-	&& chmod 755 -R /srv/shiny-server \
-	&& chown shiny:shiny -R /opt/shiny-server/samples/sample-apps /var/lib/shiny-server/bookmarks \
-	&& chmod 755 -R /opt/shiny-server/samples/sample-apps
+COPY ./scripts/shiny-customized.config /etc/shiny-server/shiny-server.conf
 
-EXPOSE 3838
+#RUN usermod -aG shiny default
+
+USER 1001
+#USER shiny
 
 # shiny account is created when installing the shiny rpm
-USER shiny
-
+#USER shiny
 ENTRYPOINT [ "/usr/bin/shiny-server" ]
+
+HEALTHCHECK --interval=10s --timeout=1s CMD curl localhost:3838 || exit 1
+
+EXPOSE 3838
